// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roaoqepeaqphtgxrlxcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvYW9xZXBlYXFwaHRneHJseGNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxMTAwNDgsImV4cCI6MjA4ODY4NjA0OH0.S4UsE2yASuw1f5SWvqGEI-gIzXtvpwUJB_OPn62anVU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});